###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Thomas J. Sargent & John Stachurski'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2021'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
execution_allow_errors = False
execution_excludepatterns = []
execution_in_temp = False
execution_timeout = 60
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book',  'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_panels', 'sphinx_book_theme', 'sphinx_multitoc_numbering', 'sphinxext.rediraffe', 'sphinx_tojupyter', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = 'https://python.quantecon.org/'
html_favicon = '_static/lectures-favicon.ico'
html_logo = '_static/qe-logo.png'
html_sourcelink_suffix = ''
html_static_path = ['_static', '_static']
html_theme = 'quantecon_book_theme'
html_theme_options = {'header_organisation_url': 'https://quantecon.org', 'header_organisation': 'QuantEcon', 'repository_url': 'https://github.com/QuantEcon/lecture-python-programming.myst', 'nb_repository_url': 'https://github.com/QuantEcon/lecture-python-programming.notebooks', 'twitter': 'quantecon', 'twitter_logo_url': 'https://assets.quantecon.org/img/qe-twitter-logo.png', 'og_logo_url': 'https://assets.quantecon.org/img/qe-og-logo.png', 'description': 'This website presents a set of lectures on python programming for economics, designed and written by Thomas J. Sargent and John Stachurski.', 'keywords': 'Python, QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski', 'google_analytics_id': 'UA-54984338-9', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': 'https://mybinder.org', 'thebe': False}}
html_title = 'Python Programming for Economics and Finance'
jupyter_cache = ''
jupyter_execute_notebooks = 'cache'
language = None
latex_engine = 'pdflatex'
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js'
myst_enable_extensions = ['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist']
myst_url_schemes = ['mailto', 'http', 'https']
nb_output_stderr = 'show'
numfig = True
panels_add_bootstrap_css = False
pygments_style = 'sphinx'
rediraffe_redirects = {'index_toc.md': 'intro.md'}
suppress_warnings = ['myst.domains']
tojupyter_image_urlpath = 'https://python-programming.quantecon.org/_static/'
tojupyter_images_markdown = True
tojupyter_kernels = {'python3': {'kernelspec': {'display_name': 'Python', 'language': 'python3', 'name': 'python3'}, 'file_extension': '.py'}}
tojupyter_lang_synonyms = ['ipython', 'ipython3', 'python']
tojupyter_static_file_path = ['source/_static', '_static']
tojupyter_target_html = True
tojupyter_urlpath = 'https://python-programming.quantecon.org/'
use_jupyterbook_latex = True
use_multitoc_numbering = True
