title: Python Programming for Economics and Finance
author: Thomas J. Sargent & John Stachurski
logo: _static/qe-logo-large.png

sphinx:
  extra_extensions: [sphinx_multitoc_numbering]
  config:
    html_theme: quantecon_book_theme
    html_static_path: ['source/_static']

html_theme: quantecon_book_theme 
   
execute:
  run_in_temp: true
