name: Debug Publishing
on: ["pull_request"]
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Deploy runner on EC2
        env:
          REPO_TOKEN: ${{ secrets.QUANTECON_SERVICES_PAT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner launch \
              --cloud=aws \
              --cloud-region=us-west-2 \
              --cloud-type=p3.2xlarge \
              --labels=cml-gpu \
              --cloud-hdd-size=40
  debug:
    needs: deploy-runner
    runs-on: [self-hosted, cml-gpu]
    container:
      image: docker://nvidia/cuda:11.2.1-devel-ubuntu20.04
      options: --gpus all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: quantecon
      - name: Install Jax and Upgrade CUDA
        shell: bash -l {0}
        run: |
          pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
          nvidia-smi
      - name: Install Git
        shell: bash -l {0}
        run: apt-get install git
      - name: Construct Test data
        shell: bash -l {0}
        run: |
          mkdir test && cd test
      - name: Commit to another Repo
        shell: bash -l {0}
        env:
          QE_SERVICES_PAT: ${{ secrets.QUANTECON_SERVICES_PAT }}
        run: |
          git clone https://quantecon-services:$QE_SERVICES_PAT@github.com/quantecon/lecture-python-programming.notebooks

          cd lecture-python-programming.notebooks
          git config user.name "QuantEcon Services"
          git config user.email "admin@quantecon.org"

          git checkout -b test
          echo 'This is a test' > data.txt
          git add data.txt
          git commit -m "This is a test"

          git remote -v # Prints:
          # origin ***github.com/owner/my-repo.git (fetch)
          # origin ***github.com/owner/my-repo.git (push)

          git push origin test
      # - name: Commit latest notebooks to lecture-python-programming.notebooks
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.QUANTECON_SERVICES_PAT }}
      #   with:
      #     source-directory: 'test'
      #     destination-repository-username: 'QuantEcon'
      #     destination-repository-name: 'lecture-python-programming.notebooks'
      #     target-branch: test
      #     commit-message: 'auto publishing updates to notebooks'
      #     destination-github-username: 'quantecon-services'
      #     user-email: services@quantecon.org
