name: Execution Tests [Google Colab, Linux]
on: [push]
  # schedule:
  #   # UTC 15:00 is early morning in Australia
  #   - cron:  '0 15 * * *'
jobs:
  execution-tests-colab-linux:
    name: Execution Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Google Colab Environment
        shell: bash -l {0}
        run: pip install -r google-colab-requirements.txt
      - name: Install Jupyter Book
        shell: bash -l {0}
        run: pip install jupyter-book quantecon-book-theme sphinx-exercise sphinx-togglebutton
      - name: Build Lectures (+ Execution Checks)
        shell: bash -l {0}
        run: jb build lectures --path-output=./ -W --keep-going
      - name: Upload Execution Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: execution-reports
          path: _build/html/reports