name: Link Checker [Anaconda, Linux]
on:
  pull_request:
    types: [opened, reopened]
  schedule:
    # UTC 12:00 is early morning in Australia
    - cron:  '0 12 * * *'
jobs:
  link-checking:
    name: Link Checking
    runs-on: "ubuntu-latest"
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          args: --accept 403 lectures/*.md
      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
      # - name: Setup Anaconda
      #   uses: conda-incubator/setup-miniconda@v3
      #   with:
      #     auto-update-conda: true
      #     auto-activate-base: true
      #     miniconda-version: 'latest'
      #     python-version: "3.12"
      #     environment-file: environment.yml
      #     activate-environment: quantecon
      # - name: Download "build" folder (cache)
      #   uses: dawidd6/action-download-artifact@v10
      #   with:
      #     workflow: cache.yml
      #     branch: main
      #     name: build-cache
      #     path: _build
      # - name: Link Checker
      #   shell: bash -l {0}
      #   run: jb build lectures --path-output=./ --builder=custom --custom-builder=linkcheck
      # - name: Upload Link Checker Reports
      #   uses: actions/upload-artifact@v4
      #   if: failure()
      #   with:
      #     name: linkcheck-reports
      #     path: _build/linkcheck